# theme: jekyll-theme-cayman

# Site settings
title: Tenloy's Blog
SEOTitle: Tenloy's Blog
header-img: img/head_bg/head_bg_2.jpg
email: luotengoto@163.com
description: "iOS开发 | Tenloy，iOS Developer | Tenloy的个人博客呀"
keyword: "Tenloy, iOS, Tenloy Blog, 博客，Swift, 编译, 计算机"
url: "https://tenloy.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: img/favicon.ico


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "iOS Developer \n 你有多自律，就会有多自由"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     false
github_username:    Tenloy


# Build settings
paginate: 15
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]


# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: a84c2a57837302767371                            #生成的clientID
#  clientSecret: 847046720bec629fbd3580d8f3cc617ab9d3a27a    #生成的clientSecret
#  repo: Tenloy.github.io    #仓库名称
#  owner: Tenloy    #github用户名
#  admin: Tenloy
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Friends
#friends: [
#  {
#    title: "wfm's github",
#    href: "https://wfm19970.github.io/"
#  },
#  {
#    title: "chenshuyao's blog",
#    href: "https://chenshuyao.cn/"
#  }
#]
